"""added img_url column in itemtable

Revision ID: 7791db561df7
Revises: 3f58ccfe4ae5
Create Date: 2026-03-18 12:19:49.387756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7791db561df7'
down_revision: Union[str, Sequence[str], None] = '3f58ccfe4ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'img_url')
    # ### end Alembic commands ###
